---
- name: Set & check infos about the underlying platform (os & packages)
  ansible.builtin.include_tasks:
    file: platform.yml
    apply:
      tags: platform
  tags: platform

- name: Create system user
  ansible.builtin.include_tasks:
    file: system_user.yml
    apply:
      tags: system_user
  tags: system_user
