---
- name: Create letsdare system group
  become: true
  ansible.builtin.group:
    name: "{{ letsdare_system_group }}"
    gid: "{{ omit if letsdare_system_group_gid in (None, omit) else letsdare_system_group_gid }}"

- name: Create letsdare system user
  become: true
  ansible.builtin.user:
    name: "{{ letsdare_system_user }}"
    uid: "{{ omit if letsdare_system_user_uid in (None, omit) else letsdare_system_user_uid }}"
    group: "{{ letsdare_system_group }}"
    groups: "{{ letsdare_system_user_additional_groups }}"
    append: true
    shell: /bin/bash
    create_home: true
