---
- name: Check if testdisk can be called
  become: true
  ansible.builtin.shell: |
    testdisk /cmd /dev/notthere analyze
  register: _testdisk_result
  failed_when: 'not "Unable to open file or device /dev/notthere" in _testdisk_result.stdout'
  changed_when: false
