---
- name: Check if testdisk can be called
  ansible.builtin.shell: |
    testdisk /version
  register: _testdisk_result
  failed_when: 'not "Version: {{ letsdare_testdisk_version }}" in _testdisk_result.stdout'
  changed_when: false
