---
- name: Create letsdare install path
  become: true
  ansible.builtin.file:
    path: "{{ letsdare_dirs_deps }}"
    state: directory
    owner: "{{ letsdare_system_user }}"
    group: "{{ letsdare_system_group }}"
    mode: "755"

- name: Setup repo packages
  ansible.builtin.include_tasks:
    file: repo_packages.yml
    apply:
      tags: repo_packages
  tags: repo_packages

- name: Setup parted
  ansible.builtin.include_tasks:
    file: parted.yml
    apply:
      tags: parted
  tags: parted

- name: Setup testdisk
  ansible.builtin.include_tasks:
    file: testdisk.yml
    apply:
      tags: testdisk
  tags: testdisk

- name: Setup ddrescue
  ansible.builtin.include_tasks:
    file: ddrescue.yml
    apply:
      tags: ddrescue
  tags: ddrescue
