---
- name: Install base dependencies for Ansible
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      # ansible
      - acl
      - gnupg

- name: Install base dependencies for letsdare
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      # letsdare
      - python3-pip
      - python3-venv
      - lzip
      # Dev
      - build-essential
      - git
      - sudo
  register: _install_base_deps_result
  until:
    - "not 'Connection timed out' in _install_base_deps_result.stderr|default('')"
    - "not 'Temporary failure resolving' in _install_base_deps_result.stderr|default('')"
  retries: 3
  delay: 60

# upstream virtualenv in Ubuntu 20.04 is broken
# https://github.com/pypa/virtualenv/issues/1873
- name: Install python virtualenv
  become: true
  ansible.builtin.pip:
    name: virtualenv
    extra_args: --upgrade
