---
- name: Create testdisk install path
  become: true
  ansible.builtin.file:
    path: "{{ letsdare_dirs_deps_testdisk }}"
    state: directory
    owner: "{{ letsdare_system_user }}"
    group: "{{ letsdare_system_group }}"
    mode: "755"

- name: Download and extract testdisk
  become: true
  ansible.builtin.unarchive:
    src: "{{ letsdare_testdisk_download_url }}"
    remote_src: true
    dest: "{{ letsdare_dirs_deps_testdisk }}"
    owner: "{{ letsdare_system_user }}"
    group: "{{ letsdare_system_group }}"
    extra_opts: "--strip-components=1"
    mode: "755"
  register: _download_and_unarchive_testdisk
  until:
    - "not 'urlopen error' in _download_and_unarchive_testdisk.msg | default('')"
    - "not 'The read operation timed out' in _download_and_unarchive_testdisk.msg | default('')"
  retries: 3
  delay: 60

- name: Deploy wrapper script
  become: true
  ansible.builtin.blockinfile:
    path: /usr/local/bin/testdisk
    mode: a+x
    create: true
    block: |
      #!/bin/bash

      {{ letsdare_dirs_deps_testdisk }}/testdisk_static $@
