---
- name: Does not converge
  hosts: all
  tasks:
    #  ----------------------------------
    - name: Should fail when Ansible version (core) is lower than supported
      block:
        - name: "Arrange&Act"
          ansible.builtin.include_role:
            name: "stevenengland.letsdare"
          tags:
            - check_ansible_version
          vars:
            ansible_version_minimum: "99.99"
      rescue:
        - name: Dummy
          ansible.builtin.debug:
            var: _exception

        - name: Assert
          ansible.builtin.assert:
            that:
              - "'must update' in _exception.msg"
    #  ----------------------------------
    - name: Should fail when host does not have all Ansible collections installed
      block:
        - name: "Arrange&Act"
          ansible.builtin.include_role:
            name: "stevenengland.letsdare"
          tags:
            - check_ansible_collections
          vars:
            ansible_required_collections:
              - test.notfound
      rescue:
        - name: Dummy
          ansible.builtin.debug:
            var: _exception

        - name: Assert
          ansible.builtin.assert:
            that:
              - "'Missing' in _exception.results[0].msg"
